"""
backend/app/services/documents/profiles/driving_license_profile.py

Driving License Reference Profile.
Initial reference profile targeting Indian Driving Licences (MoRTH / Sarathi format).
NOTE: This is an initial reference profile and does not claim universal Driving License support
across all global or state layouts.
"""
from app.services.documents.profiles.document_profile import (
    DocumentProfile,
    DocumentType,
    ModuleSupportStatus,
    ProfileStatus,
)
from app.services.document_intelligence.schema import (
    DocumentRegionType,
    ExpectedRegionConfig,
    NormalizedBBox,
    SemanticDateRole,
    SemanticFieldConfig,
    SpatialRelationship,
)

DRIVING_LICENSE_PROFILE = DocumentProfile(
    document_type=DocumentType.DRIVING_LICENSE.value,
    display_name="Driving License",
    version="0.9.0",
    status=ProfileStatus.AVAILABLE,
    description="Indian Driving Licence Reference Profile supporting field extraction, structural validation, and cross-document comparison.",
    jurisdiction="IN",
    sides_supported=["front", "back"],
    front_required=True,
    back_required=False,
    classification_config={
        "aspect_ratio": 1.58,  # Standard ISO/IEC 7810 ID-1 (CR80) card format
        "aspect_ratio_tolerance": 0.25,
        "min_signals_required": 2,
        "anchor_patterns": [
            r"\bDRIVING\s+LICEN[CS]E\b",
            r"\bUNION\s+OF\s+INDIA\b",
            r"\bFORM\s+7\b",
            r"\bMOTOR\s+VEHICLES?\s+ACT\b",
            r"\bTRANSPORT\s+DEPARTMENT\b",
            r"\bINDIAN\s+UNION\s+DRIVING\s+LICEN[CS]E\b",
        ],
        "identifier_patterns": [
            r"\b[A-Z]{2}[-\s]?[0-9]{2}[-\s]?[0-9]{4}[-\s]?[0-9]{7}\b",
            r"\bDL[-\s]?[A-Z0-9]{10,16}\b",
        ],
        "domain_tokens": [
            "cov", "nt", "tr", "lmv", "mcwg", "mcwog", "hmv",
            "trans", "non-trans", "date of issue", "validity",
            "licensing authority", "badge no",
        ],
        "mismatch_negative_patterns": [
            r"\bPASSPORT\b",
            r"\bP<[A-Z]{3}",
            r"\bVISA\b",
            r"\bREPUBLIC\s+OF\s+INDIA\s+PASSPORT\b",
            r"\bELECTION\s+COMMISSION\s+OF\s+INDIA\b",
            r"\bINCOME\s+TAX\s+DEPARTMENT\b",
        ],
    },
    expected_semantic_regions={
        "card_boundary": ExpectedRegionConfig(
            region_type=DocumentRegionType.CARD_BOUNDARY,
            side="any",
            relative_box=NormalizedBBox(0.0, 0.0, 1.0, 1.0),
            required=False,
            description="Card outer perimeter",
        ),
        "portrait": ExpectedRegionConfig(
            region_type=DocumentRegionType.PORTRAIT,
            side="front",
            relative_box=NormalizedBBox(0.04, 0.20, 0.28, 0.52),
            required=False,
            description="Bearer portrait photo zone",
        ),
        "license_number": ExpectedRegionConfig(
            region_type=DocumentRegionType.LICENSE_NUMBER,
            side="front",
            relative_box=NormalizedBBox(0.25, 0.12, 0.70, 0.15),
            required=True,
            description="License number alphanumeric band",
        ),
        "identity": ExpectedRegionConfig(
            region_type=DocumentRegionType.IDENTITY,
            side="front",
            relative_box=NormalizedBBox(0.32, 0.25, 0.65, 0.35),
            required=True,
            description="Holder identity details (Name, S/W/D of, DOB)",
        ),
        "validity": ExpectedRegionConfig(
            region_type=DocumentRegionType.VALIDITY,
            side="front",
            relative_box=NormalizedBBox(0.32, 0.55, 0.65, 0.20),
            required=False,
            description="Validity dates (Non-Transport / Transport)",
        ),
        "authority": ExpectedRegionConfig(
            region_type=DocumentRegionType.AUTHORITY,
            side="front",
            relative_box=NormalizedBBox(0.05, 0.02, 0.90, 0.15),
            required=False,
            description="State / Licensing Authority Header",
        ),
        "vehicle_class": ExpectedRegionConfig(
            region_type=DocumentRegionType.VEHICLE_CLASS,
            side="front",
            relative_box=NormalizedBBox(0.05, 0.70, 0.90, 0.25),
            required=False,
            description="Class of Vehicle (COV) endorsement table",
        ),
        "address": ExpectedRegionConfig(
            region_type=DocumentRegionType.ADDRESS,
            side="any",
            relative_box=NormalizedBBox(0.05, 0.20, 0.90, 0.50),
            required=False,
            description="Permanent or Present Address zone",
        ),
        "qr": ExpectedRegionConfig(
            region_type=DocumentRegionType.QR,
            side="back",
            relative_box=NormalizedBBox(0.60, 0.30, 0.35, 0.50),
            required=False,
            description="Security QR / Barcode area on card reverse",
        ),
    },
    modules={
        "ocr": ModuleSupportStatus.SUPPORTED,
        "validation": ModuleSupportStatus.SUPPORTED,
        "forensics": ModuleSupportStatus.SUPPORTED,
        "biometrics": ModuleSupportStatus.SUPPORTED,
        "registry": ModuleSupportStatus.SUPPORTED,
        "risk": ModuleSupportStatus.SUPPORTED,
    },
    mrz_applicable=False,
    mrz_standard=None,
    portrait_applicable=True,
    portrait_required=False,
    expected_regions={
        "photo": {"relative_x": 0.05, "relative_y": 0.20, "relative_w": 0.30, "relative_h": 0.50},
        "text_zone": {"relative_x": 0.38, "relative_y": 0.15, "relative_w": 0.58, "relative_h": 0.75},
        "background": {"relative_x": 0.05, "relative_y": 0.05, "relative_w": 0.90, "relative_h": 0.12},
    },
    field_schema=[
        "license_number",
        "docNumber",
        "name",
        "dob",
        "valid_from",
        "valid_to",
        "issuedDate",
        "expiry",
        "blood_group",
        "address",
        "vehicle_classes",
        "issuing_authority",
        "state",
    ],
    required_fields=[
        "name",
        "docNumber",
        "dob",
    ],
    semantic_fields={
        # ── IDENTITY ─────────────────────────────────────────────────────────
        "name": SemanticFieldConfig(
            field_name="name",
            display_name="Holder Name",
            region_type=DocumentRegionType.IDENTITY,
            labels=["NAME", "HOLDER'S NAME", "HOLDER NAME", "BEARER NAME", "NAME OF HOLDER"],
            patterns=[r"^[A-Z\s\.]{2,40}$"],
            negative_patterns=[
                r"\b(?:DATE|DOB|VALID|FATHER|S/O|D/O|W/O|ADDRESS|INDIAN|UNION|LICENCE|TRANSPORT|FORM\s*7)\b",
                r"\b(?:ORGAN|DONOR|BLOOD|GROUP|COV|LMV|MCWG)\b",
            ],
            normalizer_type="text",
            required=True,
            side="front",
        ),
        "dob": SemanticFieldConfig(
            field_name="dob",
            display_name="Date of Birth",
            region_type=DocumentRegionType.IDENTITY,
            labels=["DOB", "DATE OF BIRTH", "D.O.B.", "D.O.B", "BIRTH DATE", "DATE OFBIRTH"],
            date_role=SemanticDateRole.DOB,
            normalizer_type="date",
            required=True,
            side="front",
        ),
        "parentage": SemanticFieldConfig(
            field_name="parentage",
            display_name="Parent / Spouse Relation",
            region_type=DocumentRegionType.IDENTITY,
            labels=["S/O", "D/O", "W/O", "C/O", "SON OF", "DAUGHTER OF", "WIFE OF", "CARE OF", "S / O", "D / O", "W / O", "SON/DAUGHTER"],
            patterns=[r"^[A-Z\s\.]{2,40}$"],
            negative_patterns=[r"\b(?:DATE|DOB|VALID|ADDRESS|INDIAN|UNION|LICENCE|TRANSPORT)\b"],
            normalizer_type="text",
            required=False,
            side="front",
        ),
        "blood_group": SemanticFieldConfig(
            field_name="blood_group",
            display_name="Blood Group",
            region_type=DocumentRegionType.IDENTITY,
            labels=["BLOOD GROUP", "BG", "BLOOD GRP", "B.G.", "BLOOD", "B.G"],
            normalizer_type="blood_group",
            required=False,
            side="front",
        ),

        # ── LICENSE ──────────────────────────────────────────────────────────
        "license_number": SemanticFieldConfig(
            field_name="license_number",
            display_name="License Number",
            region_type=DocumentRegionType.LICENSE_NUMBER,
            labels=["DL NO", "DL NUMBER", "LICENCE NO", "LICENSE NO", "DL.NO", "D.L. NO", "DL NO.", "LICENCE NO.", "LICENSE NO."],
            patterns=[
                r"\b[A-Z]{2}[-\s]?[0-9]{2}[-\s]?(?:19|20)?[0-9]{2,4}[-\s]?[0-9]{4,8}\b",
                r"\bDL[-\s]?[A-Z0-9]{10,16}\b",
            ],
            normalizer_type="license_number",
            required=True,
            side="front",
        ),
        "issue_date": SemanticFieldConfig(
            field_name="issue_date",
            display_name="Issue Date / Valid From",
            region_type=DocumentRegionType.VALIDITY,
            labels=["ISSUE DATE", "DATE OF ISSUE", "ISSUED ON", "DOI", "ISS. DT", "VALID FROM", "VALIDITY FROM"],
            date_role=SemanticDateRole.ISSUE_DATE,
            normalizer_type="date",
            required=False,
            side="front",
        ),

        # ── VALIDITY ─────────────────────────────────────────────────────────
        "valid_to": SemanticFieldConfig(
            field_name="valid_to",
            display_name="Validity (NT) / Non-Transport Expiry",
            region_type=DocumentRegionType.VALIDITY,
            labels=["VALIDITY (NT)", "VALIDITY NT", "VALID UPTO (NT)", "VALID TILL (NT)", "NON-TRANSPORT", "NT VALIDITY", "VALIDITY NON-TRANSPORT", "VALID TILL", "VALID UPTO", "EXPIRY", "EXPIRY DATE"],
            date_role=SemanticDateRole.NON_TRANSPORT_VALIDITY,
            normalizer_type="date",
            required=False,
            side="front",
        ),
        "transport_validity": SemanticFieldConfig(
            field_name="transport_validity",
            display_name="Validity (TR) / Transport Expiry",
            region_type=DocumentRegionType.VALIDITY,
            labels=["VALIDITY (TR)", "VALIDITY TR", "VALID UPTO (TR)", "VALID TILL (TR)", "TRANSPORT", "TR VALIDITY", "VALIDITY TRANSPORT", "TR"],
            date_role=SemanticDateRole.TRANSPORT_VALIDITY,
            normalizer_type="date",
            required=False,
            side="front",
        ),

        # ── AUTHORIZATION ────────────────────────────────────────────────────
        "vehicle_classes": SemanticFieldConfig(
            field_name="vehicle_classes",
            display_name="Class of Vehicle (COV)",
            region_type=DocumentRegionType.VEHICLE_CLASS,
            labels=["COV", "CLASS OF VEHICLES", "CLASS OF VEHICLE", "VEHICLE CLASS", "COV DETAILS", "AUTHORISATION TO DRIVE"],
            normalizer_type="cov",
            required=False,
            side="front",
        ),

        # ── AUTHORITY ────────────────────────────────────────────────────────
        "issuing_authority": SemanticFieldConfig(
            field_name="issuing_authority",
            display_name="Issuing Authority",
            region_type=DocumentRegionType.AUTHORITY,
            labels=["ISSUING AUTHORITY", "LICENSING AUTHORITY", "RTO", "DTO", "TRANSPORT DEPARTMENT"],
            normalizer_type="text",
            required=False,
            side="front",
        ),
        "state": SemanticFieldConfig(
            field_name="state",
            display_name="State",
            region_type=DocumentRegionType.AUTHORITY,
            labels=["STATE", "UNION OF INDIA"],
            normalizer_type="state",
            required=False,
            side="front",
        ),

        # ── CONTACT ──────────────────────────────────────────────────────────
        "address": SemanticFieldConfig(
            field_name="address",
            display_name="Address",
            region_type=DocumentRegionType.ADDRESS,
            labels=["ADDRESS", "RESIDENTIAL ADDRESS", "PERMANENT ADDRESS", "PRESENT ADDRESS"],
            multiline=True,
            normalizer_type="text",
            required=False,
            side="any",
        ),

        # ── SECURITY ─────────────────────────────────────────────────────────
        "card_serial": SemanticFieldConfig(
            field_name="card_serial",
            display_name="Card Serial Number",
            region_type=DocumentRegionType.SECURITY,
            labels=["CARD SERIAL", "CARD NO", "SL NO", "SERIAL NO"],
            normalizer_type="text",
            required=False,
            side="any",
        ),
        "qr": SemanticFieldConfig(
            field_name="qr",
            display_name="QR Barcode",
            region_type=DocumentRegionType.QR,
            required=False,
            side="back",
        ),
    },
    validation_config={
        "profile_version": "1.0.0",
        "jurisdiction": "IN",
        "required_fields": ["name", "docNumber", "dob"],
        "identifier_rules": {
            "canonical_pattern": r"^[A-Z]{2}[0-9]{2}(?:19|20)[0-9]{2}[0-9]{7}$",
            "legacy_patterns": [
                r"^[A-Z]{2}[0-9]{2}[0-9]{7,11}$",
                r"^[A-Z]{2}[-\s]?[0-9]{2}[-\s]?(?:19|20)?[0-9]{2,4}[-\s]?[0-9]{4,8}$",
                r"^DL[-\s]?[A-Z0-9]{10,16}$",
            ],
            "plausible_pattern": r"^[A-Z]{2}[A-Z0-9\-\s/]{7,22}$",
        },
        "age_rules": {
            "class_rules": {
                "MCWOG": 16,
                "M/CYCL.WOG": 16,
                "MC WITHOUT GEAR": 16,
                "LMV": 18,
                "LMV-NT": 18,
                "MCWG": 18,
                "M/CYCL.WG": 18,
                "MC WITH GEAR": 18,
                "M/CYCL": 18,
                "3W-NT": 18,
                "3W-CAB": 18,
                "3W-GV": 18,
                "TRANS": 20,
                "HGMV": 20,
                "HPMV": 20,
                "HTV": 20,
                "HPV": 20,
                "HGV": 20,
                "MGV": 20,
                "MMV": 20,
                "MPV": 20,
                "LMV-TR": 20,
                "3W-TR": 20,
                "PSV": 20,
            },
            "default_min_age": 18,
            "max_plausible_age": 110,
        },
        "cov_rules": {
            "transport_classes": [
                "TRANS", "HGMV", "HPMV", "HTV", "HPV", "HGV",
                "MGV", "MMV", "MPV", "LMV-TR", "3W-TR", "PSV",
            ],
            "non_transport_classes": [
                "LMV", "LMV-NT", "MCWG", "MCWOG", "3W-NT",
                "3W-CAB", "3W-GV", "M/CYCL.WG", "M/CYCL.WOG",
                "MC WITH GEAR", "MC WITHOUT GEAR", "M/CYCL",
            ],
            "age_16_classes": [
                "MCWOG", "M/CYCL.WOG", "MC WITHOUT GEAR",
            ],
        },
        "chronology_rules": {
            "allow_future_dob": False,
            "allow_future_issue": False,
            "require_dob_before_issue": True,
            "require_issue_before_expiry": True,
        },
        "validity_rules": {
            "transport_requires_tr_validity": True,
            "non_transport_tr_not_applicable": True,
        },
    },
    machine_readable_config={
        "applicable": True,
        "expected_side": "back",
        "expected_region": NormalizedBBox(0.60, 0.30, 0.35, 0.50),
        "supported_symbologies": ["QR_CODE"],
        "expected_fields": [
            "license_number",
            "name",
            "dob",
            "valid_from",
            "valid_to",
            "cov",
        ],
        "cross_check_fields": [
            "license_number",
            "name",
            "dob",
            "valid_from",
            "valid_to",
            "cov",
        ],
        "crypto_verification": {
            "supported": False,
            "status": "CRYPTO_VERIFICATION_UNAVAILABLE",
            "reason": "No public key infrastructure published by MoRTH/Sarathi for offline QR verification",
        },
    },
    forensic_config={
        "supported": True,
        "applicable": True,
        "min_dimension": 450,
        "expected_aspect_ratio": 1.58,
        "aspect_tolerance": 0.25,
        "regions": {
            "card_boundary": {"required": True, "type": "CARD_BOUNDARY"},
            "portrait_area": {"relative_box": NormalizedBBox(0.05, 0.20, 0.30, 0.50), "type": "PORTRAIT"},
            "identity_text": {"relative_box": NormalizedBBox(0.38, 0.15, 0.58, 0.40), "type": "IDENTITY"},
            "license_number": {"relative_box": NormalizedBBox(0.38, 0.05, 0.58, 0.15), "type": "LICENSE_NUMBER"},
            "validity": {"relative_box": NormalizedBBox(0.38, 0.45, 0.58, 0.15), "type": "VALIDITY"},
            "vehicle_classes": {"relative_box": NormalizedBBox(0.05, 0.70, 0.90, 0.25), "type": "VEHICLE_CLASS"},
            "issuing_authority": {"relative_box": NormalizedBBox(0.05, 0.02, 0.90, 0.15), "type": "AUTHORITY"},
            "qr_area": {"relative_box": NormalizedBBox(0.60, 0.30, 0.35, 0.50), "type": "QR"},
        },
        "signals": {
            "image_quality": {"enabled": True, "min_blur": 25.0, "min_brightness": 25.0, "max_brightness": 230.0},
            "ela": {"enabled": True, "jpeg_quality": 90, "outlier_k": 2.5, "suspicious_area_ratio": 0.02},
            "compression": {"enabled": True, "inconsistency_ratio_suspicious": 5.0, "inconsistency_ratio_high": 10.0},
            "copy_move": {"enabled": True, "min_matches": 10, "min_distance_px": 50},
            "splicing_edge": {"enabled": True, "gradient_discontinuity_threshold": 35.0},
            "document_boundary": {"enabled": True, "min_rectangularity": 0.75},
            "metadata_exif": {"enabled": True},
            "ai_tampering_model": {"enabled": True, "weights_path": None},
        },
    },
    biometric_config={
        "applicable": True,
        "portrait_applicable": True,
        "portrait_source_preference": ["detector_fallback", "semantic_region"],
        "expected_portrait_region": NormalizedBBox(0.04, 0.20, 0.28, 0.52),
        "face_match_threshold": 0.40,
        "inconclusive_margin": 0.06,
        "pad_required": True,
        "pad_threshold": 0.70,
        "pad_suspect_threshold": 0.40,
        "calibration_status": "UNCALIBRATED_PROFILE_DEFAULT",
        "supported_detector": "InsightFace-SCRFD-10G",
        "supported_embedding_model": "ArcFace-w600k_r50",
        "supported_pad_model": "MiniFASNetV2",
        "allow_multiple_document_faces": False,
        "allow_multiple_live_faces": False,
    },
    registry_config={
        "applicable": True,
        "lookup_keys": ["document_number", "license_number"],
        "cross_check_fields": [
            "document_number",
            "name",
            "date_of_birth",
            "expiry_date",
            "valid_from",
            "vehicle_classes",
            "issuing_authority",
            "state",
        ],
        "providers": [
            "DEVELOPMENT_MOCK",
            "AUTHORIZED_GOVERNMENT_PROVIDER",
        ],
        "default_provider": "DEVELOPMENT_MOCK",
        "timeout_seconds": 5.0,
        "retry_policy": {
            "max_retries": 2,
            "backoff_factor": 0.5,
            "retry_on": ["TIMEOUT", "PROVIDER_UNAVAILABLE", "RATE_LIMITED"],
            "never_retry": ["UNAUTHORIZED", "INVALID_REQUEST"],
        },
        "authoritative_status_mapping": {
            "ACTIVE": "ACTIVE",
            "VALID": "ACTIVE",
            "EXPIRED": "EXPIRED",
            "SUSPENDED": "SUSPENDED",
            "REVOKED": "REVOKED",
            "CANCELLED": "REVOKED",
        },
        "jurisdiction": "IN",
    },
    risk_config={
        "category_weights": {
            "validation": 0.25,
            "forensics": 0.30,
            "biometrics": 0.25,
            "registry": 0.20,
            "machine_readable": 0.20,
        },
        "critical_thresholds": {
            "face_spoof_confirmed": 80,
            "registry_revoked": 85,
            "known_fraud_pattern": 80,
            "qr_tampered": 80,
        },
        "minimum_completeness_for_auto_clear": 0.70,
        "inconclusive_conditions": [
            "missing_both_biometrics_and_registry",
            "critical_image_quality_failure",
        ],
        "diminishing_returns": {
            "correlation_decay_factor": 0.5,
        },
    },
)


